networks:
  carwarehouse.web:
    driver: bridge

services:
  carwarehouse.web:
    image: ${DOCKER_REGISTRY-}carwarehouseweb
    build:
      context: .
      dockerfile: CarWarehouse.Web/Dockerfile
    ports:
      - "8081:8081"
      - "8080:8080"
    networks:
      - carwarehouse.web
    container_name: carwarehouse_web_api
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - carwarehouse.web
    environment:
      POSTGRES_DB: CarWarehouseDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: F33092t02.
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
