services:
  carwarehouse.web:
    image: ${DOCKER_REGISTRY-}carwarehouseweb
    build:
      context: .
      dockerfile: CarWarehouse.Web/Dockerfile
    ports:
       - "8081:8081"
       - "8080:8080"
    container_name: carwarehouse_web_api
    depends_on: 
       - db
  db:
    image: postgres:latest
    ports: 
       - "5433:5432"
    environment:
        POsTGRES_DB: CarWarehouseDb
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: F33092t02.
    container_name: db_postgressql_container
    volumes: 
       - ./.containers/products-db:/var/lib/postgresql/data


